### ISSUE TITLE
[Error] On Nexus series

### ISSUE THREAD

**Issue by dev070314** [CanOrhan/Media-Player#1]
May i know what devices you tested on the source ? Below are current log on Nexus devices. We can't run the source
04-23 16:55:44.399    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ DrmException: 0x80014036
04-23 16:55:44.399    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.microsoft.playready2.Native_Class9.method_4(Native Method)
04-23 16:55:44.399    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.microsoft.playready2.o.a(SourceFile:318)
04-23 16:55:44.399    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.microsoft.playready2.PRMediaPlayer.prepare(SourceFile:220)
04-23 16:55:44.399    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.example.mediaplayersample.adapters.v2.V2MediaPlayerAdapter.prepare(V2MediaPlayerAdapter.java:273)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.example.mediaplayersample.MediaPlayerViewModel.<init>(MediaPlayerViewModel.java:61)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.example.mediaplayersample.MainActivity.createMediaPlayer(MainActivity.java:393)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.example.mediaplayersample.MainActivity.play(MainActivity.java:488)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.example.mediaplayersample.MainActivity$11.onItemClick(MainActivity.java:346)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.widget.AdapterView.performItemClick(AdapterView.java:299)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.widget.AbsListView$3.run(AbsListView.java:3645)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.os.Handler.handleCallback(Handler.java:733)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.os.Looper.loop(Looper.java:212)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5137)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
04-23 16:55:44.409    2423-2423/com.example.mediaplayersample.mediaplayer W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)

**Comment by to-jbm** [comment]
Hi
I think we are looking for the same 
have you found a way to play playready protected streams on android ?
